# Job for checking wpiformat violations

parameters:
  jobName: ''
  pool:
    vmImage: 'Ubuntu 16.04'

jobs:
- job: Styleguide
  pool: ${{ parameters.pool }}

  container: ubuntu

  workspace:
    clean: all

  timeoutInMinutes: 0

  steps:
    - script: |
        sudo pip3 install wpiformat
      displayName: 'Install wpiformat'

    - script: |
        git checkout -b master
        wpiformat -clang 6.0
      displayName: 'Run wpiformat'

    - script: |
        # Ensure formatter made no changes
        git --no-pager diff --exit-code HEAD
      displayName: 'Check wpiformat Output'
